### PR TITLE
Create en_gb.json

### PR DESCRIPTION
**Pull request by Astratene**
Hopefully this is correct. I may have missed a spelling error between the two but as far as I am aware this should be accurate.

### CODE REVIEW

**Comment by Astratene** [comment]
BTW theendercore might single-handedly get people to do translations for this lol.

**Comment by craftish37** [comment]
lgtm, gonna merge in some hours 👌

**Comment by Astratene** [comment]
Just want to note that you linked GB incorrectly on modrinth

**Comment by theendercore** [comment]
still not corrected :cry:

**Comment by craftish37** [comment]
Corrected, thanks for the info 😅

**Comment by Astratene** [comment]
thanks a lot! I might eventually do a couple more of these as well such as pirate speak

**Pull request merged**
